export const products = {
 // categories of products
 insaat: [
  {
    name: "Tuğla",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/tugla.jpg'),
    id: "tugla1",
  },
  {
    name: "Taş",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/tas.jpg'),
    id: "tas1",
  },
  {
    name: "Çimento",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/cimento.jpg'),
    id: "cimento1"
  },
  {
    name: "PVC Boru",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/boru.jpg'),
    id: "boru1"
  },
],
tekstil: [
  {
    name: "Kumaş",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/kumas.jpg'),
    id: "kumas1",
  },
  {
    name: "Polyester",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/polyester.jpg'),
    id: "polyester1",
  },
  {
    name: "Deri",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/deri.jpg'),
    id: "deri1"
  },
  {
    name: "Yün",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/yun.jpg'),
    id: "yün1"
  },
],
kimya: [
  {
    name: "Gübre",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/gubre.jpg'),
    id: "gubre1",
  },
  {
    name: "Haşere İlacı",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/hasere.jpg'),
    id: "hasere1",
  },
  {
    name: "Hayvansal Takviye",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/hayvan.jpg'),
    id: "takviye1"
  },
  {
    name: "Sterilizasyon Kiti",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/sterilizasyon.jpg'),
    id: "sterilizasyon"
  },
],
mobilya: [
  {
    name: "Pimapen",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/pimapen.jpg'),
    id: "pimapen1",
  },
  {
    name: "Sunta",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/sunta.jpg'),
    id: "sunta1",
  },
  {
    name: "Menteşe",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/mentese.jpg'),
    id: "mentese1"
  },
  {
    name: "Çerçeve",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/cerceve.jpg'),
    id: "cerceve1"
  },
],
metalurji: [
  {
    name: "Demir",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/demir.jpg'),
    id: "demir1",
  },
  {
    name: "Çelik",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/celik.jpg'),
    id: "celik1",
  },
  {
    name: "Bakır",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/bakir.jpg'),
    id: "bakir1"
  },
  {
    name: "Alüminyum",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/aluminium.jpg'),
    id: "aluminium"
  },
],
kurugida: [
  {
    name: "Buğday",
    description: "Description 1",
    kind: "Kind 1",
    image: require('@/assets/bugday.jpg'),
    id: "bugday1",
  },
  {
    name: "Un",
    description: "Description 2",
    kind: "Kind 2",
    image: require('@/assets/un.jpg'),
    id: "un1",
  },
  {
    name: "Şeker",
    description: "Description 3",
    kind: "Kind 1",
    image: require('@/assets/seker.jpg'),
    id: "seker1"
  },
  {
    name: "Yağ",
    description: "Description 4",
    kind: "Kind 3",
    image: require('@/assets/yag.jpg'),
    id: "yag1"
  },
],

    // seller of product
  tugla1: [
    {
      title: "Tuğla",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/tugla.jpg"),
    },
    {
      title: "Tuğla 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/tugla.jpg"),
    },
    {
      title: "Tuğla 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/tugla.jpg"),
    },
  ],
  tas1: [
    {
      title: "Taş",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/tas.jpg"),
    },
    {
      title: "Taş 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/tas.jpg"),
    },
    {
      title: "Taş 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/tas.jpg"),
    },
  ],
  cimento1: [
    {
      title: "Çimento",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/cimento.jpg"),
    },
    {
      title: "Çimento 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/cimento.jpg"),
    },
    {
      title: "Çimento 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/cimento.jpg"),
    },
  ],
  boru1: [
    {
      title: "PVC Boru",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/boru.jpg"),
    },
    {
      title: "PVC Boru 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/boru.jpg"),
    },
    {
      title: "PVC Boru 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/boru.jpg"),
    },
  ],
  kumas1: [
    {
      title: "Kumaş",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/kumas.jpg"),
    },
    {
      title: "Kumaş 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/kumas.jpg"),
    },
    {
      title: "Kumaş 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/kumas.jpg"),
    },
  ],
  
  polyester1: [
    {
      title: "Polyester",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/polyester.jpg"),
    },
    {
      title: "Polyester 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/polyester.jpg"),
    },
    {
      title: "Polyester 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/polyester.jpg"),
    },
  ],
  
  deri1: [
    {
      title: "Deri",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/deri.jpg"),
    },
    {
      title: "Deri 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/deri.jpg"),
    },
    {
      title: "Deri 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/deri.jpg"),
    },
  ],
  
  yun1: [
    {
      title: "Yün",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/yun.jpg"),
    },
    {
      title: "Yün 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/yun.jpg"),
    },
    {
      title: "Yün 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/yun.jpg"),
    },
  ],
  gubre1: [
    {
      title: "Gübre",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/gubre.jpg"),
    },
    {
      title: "Gübre 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/gubre.jpg"),
    },
    {
      title: "Gübre 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/gubre.jpg"),
    },
  ],
  
  hasere1: [
    {
      title: "Haşere İlacı",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/hasere.jpg"),
    },
    {
      title: "Haşere İlacı 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/hasere.jpg"),
    },
    {
      title: "Haşere İlacı 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/hasere.jpg"),
    },
  ],
  
  takviye1: [
    {
      title: "Hayvansal Takviye",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/hayvan.jpg"),
    },
    {
      title: "Hayvansal Takviye 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/hayvan.jpg"),
    },
    {
      title: "Hayvansal Takviye 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/hayvan.jpg"),
    },
  ],
  
  sterilizasyon: [
    {
      title: "Sterilizasyon Kiti",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/sterilizasyon.jpg"),
    },
    {
      title: "Sterilizasyon Kiti 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/sterilizasyon.jpg"),
    },
    {
      title: "Sterilizasyon Kiti 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/sterilizasyon.jpg"),
    },
  ],
  
  pimapen1: [
    {
      title: "Pimapen",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/pimapen.jpg"),
    },
    {
      title: "Pimapen 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/pimapen.jpg"),
    },
    {
      title: "Pimapen 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/pimapen.jpg"),
    },
  ],
  
  sunta1: [
    {
      title: "Sunta",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/sunta.jpg"),
    },
    {
      title: "Sunta 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/sunta.jpg"),
    },
    {
      title: "Sunta 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/sunta.jpg"),
    },
  ],
  
  mentese1: [
    {
      title: "Menteşe",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/mentese.jpg"),
    },
    {
      title: "Menteşe 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/mentese.jpg"),
    },
    {
      title: "Menteşe 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/mentese.jpg"),
    },
  ],
  
  cerceve1: [
    {
      title: "Çerçeve",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/cerceve.jpg"),
    },
    {
      title: "Çerçeve 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/cerceve.jpg"),
    },
    {
      title: "Çerçeve 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/cerceve.jpg"),
    },
  ],
  
  demir1: [
    {
      title: "Demir",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/demir.jpg"),
    },
    {
      title: "Demir 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/demir.jpg"),
    },
    {
      title: "Demir 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/demir.jpg"),
    },
  ],
  
  celik1: [
    {
      title: "Çelik",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/celik.jpg"),
    },
    {
      title: "Çelik 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/celik.jpg"),
    },
    {
      title: "Çelik 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/celik.jpg"),
    },
  ],
  
  bakir1: [
    {
      title: "Bakır",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/bakir.jpg"),
    },
    {
      title: "Bakır 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/bakir.jpg"),
    },
    {
      title: "Bakır 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/bakir.jpg"),
    },
  ],
  
  aluminium: [
    {
      title: "Alüminyum",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/aluminium.jpg"),
    },
    {
      title: "Alüminyum 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/aluminium.jpg"),
    },
    {
      title: "Alüminyum 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/aluminium.jpg"),
    },
  ],
  
  bugday1: [
    {
      title: "Buğday",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/bugday.jpg"),
    },
    {
      title: "Buğday 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/bugday.jpg"),
    },
    {
      title: "Buğday 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/bugday.jpg"),
    },
  ],
  
  un1: [
    {
      title: "Un",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/un.jpg"),
    },
    {
      title: "Un 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/un.jpg"),
    },
    {
      title: "Un 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/un.jpg"),
    },
  ],
  
  seker1: [
    {
      title: "Şeker",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/seker.jpg"),
    },
    {
      title: "Şeker 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/seker.jpg"),
    },
    {
      title: "Şeker 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/seker.jpg"),
    },
  ],
  
  yag1: [
    {
      title: "Yağ",
      description: "Satıcı 1'in en iyi malları",
      sellerName: "Satıcı 1",
      price: 100,
      amount: 5,
      image: require("@/assets/yag.jpg"),
    },
    {
      title: "Yağ 2",
      description: "Description for Ad 2",
      sellerName: "Satıcı 2",
      price: 150,
      amount: 8,
      image: require("@/assets/yag.jpg"),
    },
    {
      title: "Yağ 3",
      description: "Description for Ad 3",
      sellerName: "Satıcı 3",
      price: 120,
      amount: 10,
      image: require("@/assets/yag.jpg"),
    },
  ],
  
};
